import React from 'react';
import {withStyles} from '@material-ui/core/styles';
import {
    Edit,
    TextInput,
    SimpleForm,
    required,
    DisabledInput,
    DateInput
} from 'react-admin';

// Create custom styles for the page.
const styles = {
    root: {
        alignItems: 'left',
    },
    inlineBlock: {
        display: 'inline-flex',
        marginRight: '1rem',
    },
};

const ProfileEdit = ({ classes, staticContext, ...props }) => {
    return (
        <Edit
            align="left"
            /*
                As this component isn't loaded from a route generated by a <Resource>,
                I have to provide the id myself.
                As there is only one config for the current user, I decided to
                hard-code it here
            */
            id="my-profile"
            /*
                For the same reason, I need to provide the resource and basePath props
                which are required by the Edit component
            */
            resource="Profile"
            basePath="/my-profile"
            redirect={false}
            /*
                I also customized the page title as it'll make more sense to the user
            */
            title="My profile"
            {...props}
        >
            <SimpleForm>
                <DisabledInput label="UUID" source="id" />
                <TextInput
                    label="First Name"
                    source="fname"
                    validate={required()}
                />
                <TextInput
                    label="Last Name"
                    source="lname"
                    validate={required()}
                />
                <TextInput
                    label="Email Address"
                    source="email"
                    type="email"
                    validate={required()}
                />
                <DateInput
                    source="activated_at"
                    disabled="true"
                    defaultValue={new Date()}
                />
            </SimpleForm>
        </Edit>
    )
};

export default withStyles(styles)(ProfileEdit);